version: '3.8'

services:
  # Python API (Backend)
  backend:
    image: devops-backend:latest
    restart: unless-stopped
    expose:
      - "5000"

  # Nginx Web Server (Frontend)
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'

  # --- PROMETHEUS STORAGE INITIALIZER ---
  prometheus-init:
    image: alpine:latest
    user: "root"
    volumes:
      - ./prometheus_data:/prometheus
    command: chown -R 65534:65534 /prometheus

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
    depends_on:
      backend:
        condition: service_started
      node-exporter:
        condition: service_started
      prometheus-init:
        condition: service_completed_successfully

  # --- GRAFANA STORAGE INITIALIZER ---
  grafana-init:
    image: alpine:latest
    user: "root"
    volumes:
      - ./grafana_data:/var/lib/grafana
    command: chown -R 472:472 /var/lib/grafana

  # Grafana
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ahmedongrafana.1
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards/default.yml:/etc/grafana/provisioning/dashboards/default.yml:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      prometheus:
        condition: service_started
      grafana-init:
        condition: service_completed_successfully