sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.organization=${env.SONAR_ORGANIZATION}
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=api
sonar.tests=api
sonar.test.inclusions=api/test_*.py
sonar.coverage.exclusions=api/test_*.py,website/**/*,ansible/**/*,*.tf,*.yml,*.md,**/__init__.py,api/downloads/**/*