name: "Terraform Destroy"

on:
  workflow_dispatch: # This adds a manual "Run" button in GitHub Actions

jobs:
  terraform-destroy:
    name: "Destroy AWS Infra"
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Prevents the pipeline from hanging forever if a cloud API stalls
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=kali-terraform-state-storage-2026" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          TF_VAR_grafana_admin_user: ${{ secrets.GRAFANA_ADMIN_USER }}
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          TF_VAR_domain_name: "ytthumbnail.site"
          TF_VAR_subdomain_name: "www"
          TF_VAR_user_name: "kali"
          TF_VAR_instance_type: "t3.micro"